app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    hash_password = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('this property cannot be accessed')

    @password.setter
    def password(self, password):
        self.hash_password= generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.hash_password, password)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap

login_manager = LoginManager()
bootstrap = Bootstrap()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

db = SQLAlchemy()

def create_app(config_name):

    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(config_options[config_name])

    # flask extensions
    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)

    # register blueprints
    from .auth import auth as auth_bp
    app.register_blueprint(auth_bp)

    from .main import main as main_bp
    app.register_blueprint(main_bp)



    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template
from . import main

@main.route('/')
def index():
    title = 'Pomodoro'
    return render_template('main/index.html', title = title)

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  {% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
  <main>
    {% block main %}{% endblock %}
  </main>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  {% block script %}{% endblock %}
</body>

</html>

app/templates/main/index.html
{% extends 'base.html'%}
{% block title %}Home{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
       <div class="col-sm-12">
           {{title}}
       </div>
    </div>
</div>

{% endblock%}%  

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <a class="navbar-brand" href="{{url_for('main.index')}}">Pompoms</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">        
        <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.register')}}">Sign in</a>
          </li>
      </ul>
    </div>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.logout')}}">Sign out</a>
        </li>
      </ul>
    </div>

  </nav>